version: '3.8'

services:
   nginx:
      depends_on: 
         - client
         - backend
      build:
         context: ./nginx
         # target: prod
      restart: always
      ports:
         - 80:80
   client:
      container_name: client
      build:
         context: ./client
         target: prod
      volumes:
         - '/app/node_modules'
      restart: on-failure
   backend:
      build:
         context: ./backend
         # target: prod
      container_name: backend

