version: '3.8'

services:
   nginx:
      depends_on: 
         - client
         - backend
      build: ./nginx
      restart: always
      ports:
         - 80:80
   client:
      container_name: client
      build: ./client
      volumes:
         - '/app/node_modules'
      restart: on-failure
   backend:
      build: ./backend
      container_name: backend
      env_file: 
         - ./env/
   mongo:
      image: mongo
      container_name: mongo-db
      ports:
         - 27017:27017
      volumes: 
         - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
         - ./db/mongo-volume:/data/db
      env_file: 
         - ./env/
