version: '3.8'

services:

   # ---------NGINX---------
   nginx:
      depends_on: 
         - client
         - backend
      image: forestcorgi/merkado_nginx
      container_name: merkado_nginx
      build:
         context: ./nginx
      restart: always
      ports:
         - 80:80

   # --------CLIENT----------
   client:
      image: forestcorgi/merkado_client
      container_name: merkado_client
      build:
         context: ./client
         dockerfile: Dockerfile.prod
      volumes:
         - '/app/node_modules'
      restart: on-failure

   # ---------BACKEND---------
   backend:
      image: forestcorgi/merkado_backend
      build:
         context: ./backend
      container_name: merkado_backend
      
