# serverless.yml

service: apollo-lambda
useDotenv: true
frameworkVersion: ^2.52.1

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: app.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
  